"""
trainer.py
QLoRA fine-tuning of Qwen2.5-3B-Instruct on intent classification.
Designed for Google Colab T4 GPU (16GB VRAM) — uses 4-bit quantization (BitsAndBytes) + LoRA (PEFT) 
So model can be trained and saved within 16GB VRAM limit.

Key decisions:
  - Uses SFTConfig (not TrainingArguments) as required by modern trl
  - Pushes final LoRA adapter to HuggingFace Hub after training
  - Reads HF token from environment variable (never hardcoded)
  - dataset["text"] field alignment with dataset.py output
  - packing=False (short intent sequences — no benefit from packing)
  - Colab-safe: no multiprocessing, Drive persistence, memory cleanup
"""

from __future__ import annotations

import gc
import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

import torch
from model.intent.dataset import get_dataset_path
from datasets import DatasetDict, load_from_disk
from peft import (
    LoraConfig,
    PeftModel,
    TaskType,
    get_peft_model,
    prepare_model_for_kbit_training,
)
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    EarlyStoppingCallback,
    TrainerCallback,
    TrainingArguments,
)
from trl import SFTTrainer

 
# Config dataclass 


@dataclass
class TrainingConfig:
    """
    All training hyperparameters in one place.

    HuggingFace push:
      - hub_repo_id   : your HF repo e.g. "your-username/transport-agent-intent"
      - HF_WRITE_TOKEN: read from environment (set in Colab secrets or .env)
                        never hardcoded here

    Dataset:
      - dataset_text_field must match the column name in dataset.py output
        (dataset.py generates a "text" column — do not change this)
    """

    # Model
    model_name: str = "Qwen/Qwen2.5-3B-Instruct"
    dataset_path: str = field(default_factory=get_dataset_path)

    #  Dataset field ─
    # Must match the column generated by dataset.py
    dataset_text_field: str = "text"

    #  Output — Google Drive paths for Colab persistence ─
    output_dir: str = "/content/drive/MyDrive/transport_agent/checkpoints"
    final_adapter_dir: str = "/content/drive/MyDrive/transport_agent/lora_adapter"
    logs_dir: str = "/content/drive/MyDrive/transport_agent/logs"

    #  HuggingFace Hub push 
    # Set to your HF username/repo — adapter will be pushed here after training
    hub_repo_id: str = "Elbana22/transport-agent-intent"
    # Token is read from env var HF_WRITE_TOKEN — never put token here
    push_to_hub: bool = True

    #  LoRA 
    lora_r: int = 16            # rank — balance between capacity and size
    lora_alpha: int = 32        # scaling = alpha/r = 2x
    lora_dropout: float = 0.05
    # Must be List[str] not tuple — required for JSON serialization + PEFT
    lora_target_modules: List[str] = field(default_factory=lambda: [
        "c_attn", "c_proj",  # GPT-2 style layers
    ])

    #  Quantization (4-bit for T4) 
    load_in_4bit: bool = False  # Disable for GPT-2 compatibility
    bnb_4bit_compute_dtype: str = "float16"
    # nf4 is required for double quantization (use_nested_quant)
    # if you change to fp4, set use_nested_quant=False
    bnb_4bit_quant_type: str = "nf4"
    use_nested_quant: bool = True   # double quant — only valid with nf4

    #  Training 
    num_epochs: int = 3
    per_device_train_batch_size: int = 2
    per_device_eval_batch_size: int = 2
    gradient_accumulation_steps: int = 8    # effective batch size = 16
    learning_rate: float = 2e-4
    warmup_ratio: float = 0.05
    weight_decay: float = 0.01
    max_grad_norm: float = 0.3
    lr_scheduler_type: str = "cosine"

    #  Sequence length 
    # 512 is enough for: system prompt + user query + intent JSON output
    # Intent JSON is ~200 tokens max — do not reduce below 384
    max_seq_length: int = 512

    #  Evaluation & saving 
    eval_steps: int = 50
    save_steps: int = 50
    logging_steps: int = 10
    load_best_model_at_end: bool = True
    metric_for_best_model: str = "eval_loss"
    early_stopping_patience: int = 5

    #  Misc 
    seed: int = 42
    fp16: bool = True
    # paged_adamw_8bit: memory-efficient, designed for QLoRA
    optim: str = "paged_adamw_8bit"

    def __post_init__(self) -> None:
        """Validate config after init."""
        # double quant only works with nf4
        if self.use_nested_quant and self.bnb_4bit_quant_type != "nf4":
            raise ValueError(
                "use_nested_quant=True requires bnb_4bit_quant_type='nf4'. "
                f"Got: '{self.bnb_4bit_quant_type}'. "
                "Either set bnb_4bit_quant_type='nf4' or use_nested_quant=False."
            )
        # validate compute dtype string
        valid_dtypes = {"float16", "bfloat16", "float32"}
        if self.bnb_4bit_compute_dtype not in valid_dtypes:
            raise ValueError(
                f"bnb_4bit_compute_dtype must be one of {valid_dtypes}. "
                f"Got: '{self.bnb_4bit_compute_dtype}'"
            )



# Callbacks



class SaveAdapterCallback(TrainerCallback):
    """
    Saves only the LoRA adapter (not full model) after each checkpoint.
    Keeps Google Drive usage low (~50MB vs ~7GB for full model).

    Saves to: final_adapter_dir/step_{N}/
    Final adapter is saved separately at end of training.
    """

    def __init__(self, adapter_save_dir: str) -> None:
        self.adapter_save_dir = Path(adapter_save_dir)

    def on_save(self, args, state, control, **kwargs) -> None:
        model = kwargs.get("model")
        if model is not None:
            step_dir = self.adapter_save_dir / f"step_{state.global_step}"
            step_dir.mkdir(parents=True, exist_ok=True)
            model.save_pretrained(str(step_dir))
            print(f"\n[SaveAdapter] LoRA adapter saved → {step_dir}")
        return control


class MemoryMonitorCallback(TrainerCallback):
    """
    Logs GPU memory usage every 50 steps.
    Useful in Colab to catch OOM before it crashes.
    """

    def on_log(self, args, state, control, logs=None, **kwargs) -> None:
        if torch.cuda.is_available() and state.global_step % 50 == 0:
            allocated = torch.cuda.memory_allocated() / 1e9
            reserved  = torch.cuda.memory_reserved() / 1e9
            print(
                f"\n[GPU] Step {state.global_step}: "
                f"Allocated={allocated:.2f}GB  Reserved={reserved:.2f}GB"
            )
        return control



# Main trainer class



class IntentModelTrainer:
    """
    Full QLoRA training pipeline for Qwen2.5-3B-Instruct intent model.

    Pipeline:
      1. Validate dataset has required "text" column
      2. Load base model with 4-bit quantization (BitsAndBytes)
      3. Apply LoRA adapters via PEFT
      4. Train with SFTTrainer (trl) — resume from checkpoint if available
      5. Save final adapter locally (Google Drive)
      6. Push adapter to HuggingFace Hub (optional)
      7. Save training metadata JSON
      8. GPU memory cleanup
    """

    def __init__(self, config: TrainingConfig) -> None:
        self.config = config
        self._setup_dirs()
        self._hf_token: Optional[str] = None

    def _setup_dirs(self) -> None:
        """Create output directories if they don't exist."""
        for d in [
            self.config.output_dir,
            self.config.final_adapter_dir,
            self.config.logs_dir,
        ]:
            Path(d).mkdir(parents=True, exist_ok=True)

    #  BitsAndBytes quantization config 

    def _get_bnb_config(self) -> BitsAndBytesConfig:
        """
        4-bit quantization config for T4 GPU.
        nf4 + double quantization = maximum memory savings.
        """
        dtype_map = {
            "float16": torch.float16,
            "bfloat16": torch.bfloat16,
            "float32": torch.float32,
        }
        return BitsAndBytesConfig(
            load_in_4bit=self.config.load_in_4bit,
            bnb_4bit_compute_dtype=dtype_map[self.config.bnb_4bit_compute_dtype],
            bnb_4bit_quant_type=self.config.bnb_4bit_quant_type,
            bnb_4bit_use_double_quant=self.config.use_nested_quant,
        )

    #  Model + tokenizer loading 

    def _load_model_and_tokenizer(self):
        """
        Load Qwen2.5-3B-Instruct with 4-bit quantization + tokenizer.

        Important:
          - padding_side="right" required for causal LM training
          - pad_token set to eos_token (Qwen2.5 has no pad token by default)
          - use_cache=False required during training (incompatible with grad checkpointing)
        """
        print(f"[Model] Loading: {self.config.model_name}")

        tokenizer = AutoTokenizer.from_pretrained(
            self.config.model_name,
            trust_remote_code=True,
            padding_side="right",   # required for causal LM training
        )

        # Qwen2.5 has no pad token — use eos token as pad
        if tokenizer.pad_token is None:
            tokenizer.pad_token    = tokenizer.eos_token
            tokenizer.pad_token_id = tokenizer.eos_token_id
            print("[Tokenizer] pad_token set to eos_token")

        if self.config.load_in_4bit:
            model = AutoModelForCausalLM.from_pretrained(
                self.config.model_name,
                quantization_config=self._get_bnb_config(),
                device_map="auto",
                trust_remote_code=True,
                torch_dtype=torch.float16,
            )
            # Required before applying LoRA with 4-bit quantization
            model = prepare_model_for_kbit_training(
                model,
                use_gradient_checkpointing=True,
            )
        else:
            model = AutoModelForCausalLM.from_pretrained(
                self.config.model_name,
                device_map="auto",
                trust_remote_code=True,
                torch_dtype=torch.float16,
            )
            model = prepare_model_for_kbit_training(
                model,
                use_gradient_checkpointing=True,
            )
        # Disable KV cache — incompatible with gradient checkpointing
        model.config.use_cache = False

        total_params     = model.num_parameters(only_trainable=False)
        trainable_params = model.num_parameters(only_trainable=True)
        print(
            f"[Model] Total params: {total_params:,} | "
            f"Trainable (before LoRA): {trainable_params:,}"
        )
        return model, tokenizer

    #  LoRA application 

    def _apply_lora(self, model) -> PeftModel:
        """
        Apply LoRA adapters to attention + FFN layers.

        target_modules covers:
          - Attention: q_proj, k_proj, v_proj, o_proj
          - FFN:       gate_proj, up_proj, down_proj (SwiGLU architecture)
        """
        lora_config = LoraConfig(
            task_type=TaskType.CAUSAL_LM,
            r=self.config.lora_r,
            lora_alpha=self.config.lora_alpha,
            lora_dropout=self.config.lora_dropout,
            target_modules=self.config.lora_target_modules,   # already List[str]
            bias="none",
            inference_mode=False,
        )
        model = get_peft_model(model, lora_config)

        # Prints: trainable params vs total — expect ~1-2% trainable
        model.print_trainable_parameters()
        return model

    #  Checkpoint resume 

    def _find_latest_checkpoint(self) -> Optional[str]:
        """
        Scan output_dir for the latest checkpoint-N folder.
        Returns path string or None if no checkpoints found.
        Enables seamless resume after Colab disconnection.
        """
        output_path = Path(self.config.output_dir)
        checkpoints = sorted(
            [
                d for d in output_path.iterdir()
                if d.is_dir() and d.name.startswith("checkpoint-")
            ],
            key=lambda x: int(x.name.split("-")[-1]),
        )
        if checkpoints:
            latest = str(checkpoints[-1])
            print(f"[Resume] Found checkpoint → {latest}")
            return latest

        print("[Resume] No checkpoint found — starting fresh")
        return None

    #  TrainingArguments for SFTTrainer 

    def _get_training_args(self) -> TrainingArguments:
        """
        Build TrainingArguments for SFTTrainer (trl 0.7.4).
        """
        return TrainingArguments(
            #  Output 
            output_dir=self.config.output_dir,

            #  Training duration 
            num_train_epochs=self.config.num_epochs,
            per_device_train_batch_size=self.config.per_device_train_batch_size,
            per_device_eval_batch_size=self.config.per_device_eval_batch_size,
            gradient_accumulation_steps=self.config.gradient_accumulation_steps,

            #  Optimizer 
            learning_rate=self.config.learning_rate,
            warmup_ratio=self.config.warmup_ratio,
            weight_decay=self.config.weight_decay,
            max_grad_norm=self.config.max_grad_norm,
            lr_scheduler_type=self.config.lr_scheduler_type,
            optim=self.config.optim,
            fp16=self.config.fp16,

            #  Evaluation 
            evaluation_strategy="steps",
            eval_steps=self.config.eval_steps,

            #  Checkpointing 
            save_strategy="steps",
            save_steps=self.config.save_steps,
            save_total_limit=3,             # keep last 3 checkpoints only

            #  Best model 
            load_best_model_at_end=self.config.load_best_model_at_end,
            metric_for_best_model=self.config.metric_for_best_model,
            greater_is_better=False,        # lower loss = better model

            #  Logging 
            logging_dir=self.config.logs_dir,
            logging_steps=self.config.logging_steps,
            report_to="none",               # disable wandb/tensorboard

            #  Misc 
            seed=self.config.seed,
            dataloader_num_workers=0,       # avoid multiprocessing issues
            remove_unused_columns=False,    # keep all columns
        )

    #  HuggingFace Hub push 

    def _push_to_hub(self, model: PeftModel, tokenizer: AutoTokenizer) -> None:
        """
        Push LoRA adapter + tokenizer to HuggingFace Hub.

        Reads HF_WRITE_TOKEN from environment.
        Token must have WRITE permission to hub_repo_id.

        Set in Colab via:
          from google.colab import userdata
          os.environ["HF_WRITE_TOKEN"] = userdata.get("HF_WRITE_TOKEN")

        Or in .env file (local dev only — never commit token).
        """
        if not self.config.push_to_hub:
            print("[Hub] push_to_hub=False — skipping HF push")
            return

        # Read token from environment — never from config
        token = os.environ.get("HF_WRITE_TOKEN")
        if not token:
            print(
                "[Hub] WARNING: HF_WRITE_TOKEN not found in environment. "
                "Skipping HF push. Set os.environ['HF_WRITE_TOKEN'] in Colab."
            )
            return

        print(f"\n[Hub] Pushing adapter to: {self.config.hub_repo_id}")
        try:
            model.push_to_hub(
                self.config.hub_repo_id,
                token=token,
                commit_message="QLoRA adapter — intent model training",
            )
            tokenizer.push_to_hub(
                self.config.hub_repo_id,
                token=token,
                commit_message="Tokenizer for intent model",
            )
            print(f"[Hub] ✅ Pushed successfully → "
                  f"https://huggingface.co/{self.config.hub_repo_id}")
        except Exception as e:
            # Don't crash training if push fails — adapter is already saved locally
            print(f"[Hub] ❌ Push failed: {e}")
            print("[Hub] Adapter is still saved locally at: "
                  f"{self.config.final_adapter_dir}")

    #  Dataset validation 

    @staticmethod
    def _validate_dataset(dataset: DatasetDict, text_field: str) -> None:
        """
        Validate dataset has required structure before training starts.
        Fails fast with clear error message instead of cryptic crash mid-training.

        Checks:
          - "train" split exists
          - "validation" split exists
          - text_field column exists in both splits
          - At least 10 training examples (sanity check)
        """
        required_splits = {"train", "validation"}
        missing_splits = required_splits - set(dataset.keys())
        if missing_splits:
            raise ValueError(
                f"Dataset missing splits: {missing_splits}. "
                f"Found: {list(dataset.keys())}. "
                "Re-run dataset.py to regenerate."
            )

        for split in required_splits:
            if text_field not in dataset[split].column_names:
                raise ValueError(
                    f"Dataset split '{split}' missing '{text_field}' column. "
                    f"Found columns: {dataset[split].column_names}. "
                    "Check dataset.py — it must create a 'text' column."
                )

        if len(dataset["train"]) < 10:
            raise ValueError(
                f"Training set too small: {len(dataset['train'])} examples. "
                "Need at least 10. Re-run dataset.py with more seeds."
            )

        print(
            f"[Dataset] ✅ Validated — "
            f"Train: {len(dataset['train'])} | "
            f"Val: {len(dataset['validation'])}"
        )

    #  Main training pipeline 

    def train(self) -> None:
        """
        Full training pipeline.

        Steps:
          1. Load + validate dataset
          2. Load model with 4-bit quantization
          3. Apply LoRA adapters
          4. Check for resume checkpoint
          5. Build SFTTrainer with SFTConfig
          6. Train (with resume support)
          7. Save final adapter locally
          8. Push to HuggingFace Hub
          9. Save training_meta.json
          10. Memory cleanup
        """

        #  Step 1: Load + validate dataset 
        print("=" * 60)
        print("[Step 1] Loading dataset...")
        dataset = load_from_disk(self.config.dataset_path)
        self._validate_dataset(dataset, self.config.dataset_text_field)

        #  Step 2: Load model 
        print("\n[Step 2] Loading model with 4-bit quantization...")
        model, tokenizer = self._load_model_and_tokenizer()

        #  Step 3: Apply LoRA 
        print("\n[Step 3] Applying LoRA adapters...")
        model = self._apply_lora(model)

        #  Step 4: Check for resume checkpoint 
        print("\n[Step 4] Checking for resume checkpoint...")
        resume_from = self._find_latest_checkpoint()

        #  Step 5: Build SFTTrainer 
        print("\n[Step 5] Building SFTTrainer...")
        callbacks = [
            SaveAdapterCallback(self.config.final_adapter_dir),
            MemoryMonitorCallback(),
            EarlyStoppingCallback(
                early_stopping_patience=self.config.early_stopping_patience
            ),
        ]

        trainer = SFTTrainer(
            model=model,
            tokenizer=tokenizer,
            train_dataset=dataset["train"],
            eval_dataset=dataset["validation"],
            dataset_text_field=self.config.dataset_text_field,
            max_seq_length=self.config.max_seq_length,
            args=self._get_training_args(),
            callbacks=callbacks,
        )

        #  Step 6: Train 
        print("\n[Step 6] Starting training...")
        print("=" * 60)
        trainer.train(resume_from_checkpoint=resume_from)

        #  Step 7: Save final adapter locally 
        print("\n[Step 7] Saving final LoRA adapter locally...")
        final_dir = Path(self.config.final_adapter_dir)
        trainer.model.save_pretrained(str(final_dir))
        tokenizer.save_pretrained(str(final_dir))
        print(f"[Save] Adapter saved → {final_dir}")

        #  Step 8: Push to HuggingFace Hub 
        print("\n[Step 8] Pushing to HuggingFace Hub...")
        self._push_to_hub(trainer.model, tokenizer)

        #  Step 9: Save training metadata 
        print("\n[Step 9] Saving training metadata...")
        meta = {
            "model_name":          self.config.model_name,
            "lora_r":              self.config.lora_r,
            "lora_alpha":          self.config.lora_alpha,
            "lora_target_modules": self.config.lora_target_modules,  # List[str] ✅
            "train_examples":      len(dataset["train"]),
            "val_examples":        len(dataset["validation"]),
            "epochs":              self.config.num_epochs,
            "max_seq_length":      self.config.max_seq_length,
            "dataset_text_field":  self.config.dataset_text_field,
            "hub_repo_id":         self.config.hub_repo_id,
            # hub_push_status recorded for traceability
            "hub_pushed":          self.config.push_to_hub,
        }
        meta_path = final_dir / "training_meta.json"
        with open(meta_path, "w", encoding="utf-8") as f:
            json.dump(meta, f, indent=2, ensure_ascii=False)
        print(f"[Meta] Saved → {meta_path}")

        #  Step 10: Memory cleanup 
        print("\n[Step 10] Cleaning up GPU memory...")
        del trainer
        del model
        gc.collect()
        torch.cuda.empty_cache()
        if torch.cuda.is_available():
            print(
                f"[GPU] After cleanup: "
                f"{torch.cuda.memory_allocated() / 1e9:.2f}GB allocated"
            )

        print("\n" + "=" * 60)
        print("✅ Training complete!")
        print(f"   Adapter : {self.config.final_adapter_dir}")
        print(f"   HF Hub  : https://huggingface.co/{self.config.hub_repo_id}")
        print("=" * 60)



# Entry point



if __name__ == "__main__":
    config = TrainingConfig()
    trainer = IntentModelTrainer(config)
    trainer.train()